version: "3.9"

services:
  database:
    container_name: database
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: vk_intern
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_ROOT_HOST: '%'
      MYSQL_PORT: 3307
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - restApiNetwork

networks:
  restApiNetwork: