version: "3.9"

services:
  database:
    container_name: database
    image: mariadb
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: vk_intern
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_ROOT_HOST: '%'
      MYSQL_PORT: 3307
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - restApiNetwork

  restapi:
    image: 'restapi:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: restapi
    restart: on-failure
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      - server.port=8080
      - spring.datasource.username=admin
      - spring.datasource.password=admin
      - REST_API_DB_IP=database
      - REST_API_DB_PORT=3307
      - spring.datasource.url=jdbc:mariadb://host.docker.internal:3307/vk_intern
    depends_on:
      - database
    networks:
      - restApiNetwork


networks:
  restApiNetwork:
