spring:
  cloud:
    openfeign:
      client:
        config:
          userHolder:
            url: https://jsonplaceholder.typicode.com/users
          postHolder:
            url: https://jsonplaceholder.typicode.com/posts
          albumHolder:
            url: https://jsonplaceholder.typicode.com/albums
  datasource:
    url: jdbc:mysql://sql11.freesqldatabase.com:3306/sql11690866
    username: sql11690866
    password: WCYCb7Usi3
  main:
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080