spring:
  cloud:
    openfeign:
      client:
        config:
          userHolder:
            url: https://jsonplaceholder.typicode.com/users
          postHolder:
            url: https://jsonplaceholder.typicode.com/posts
          albumHolder:
            url: https://jsonplaceholder.typicode.com/albums
  datasource:
    url: jdbc:mariadb://${REST_API_DB_IP:localhost}:${REST_API_DB_PORT:3306}/vk_intern
    username: admin
    password: admin
  main:
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

server:
  port: 8080