name: Run JUnit tests

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest

#    services:
#      mariadb:
#        image: mariadb-latest
#        ports:
#          - 3306:3306
#        env:
#          MARIADB_ROOT_PASSWORD: admin
#          MARIADB_DATABASE: vk_intern
#          MARIADB_USER: admin
#          MARIADB_PASSWORD: admin
#          options: --health-cmd="healthcheck.sh --connect --innodb_initialized" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Create DB
        run: docker run -p 127.0.0.1:3307:3307  --name mdb -e MARIADB_ROOT_PASSWORD=admin -d mariadb:latest
             docker exec -it mdb mariadb --user admin -p admin

      - name: Build with Maven
        run: mvn -B package --file pom.xml